#!/bin/sh

VERSION_FILE="version.txt"

version=$(cat $VERSION_FILE)

major=$(echo "$version" | cut -d. -f1)
minor=$(echo "$version" | cut -d. -f2)
patch=$(echo "$version" | cut -d. -f3)

patch=$((patch+1))

new_version="$major.$minor.$patch"

echo $new_version > $VERSION_FILE

git add $VERSION_FILE

echo "Version updated to $new_version"

exit 0
