#!/bin/sh

MSG_FILE=$1
COMMIT_SOURCE=$2
if [ "$COMMIT_SOURCE" = "merge" ] || [ "$COMMIT_SOURCE" = "commit" ]; then
  exit 0
fi

VERSION=$(cat version.txt)

FIRST=$(head -1 "$MSG_FILE")
tail -n +2 "$MSG_FILE" > "$MSG_FILE.tmp"
echo "[v$VERSION] $FIRST" > "$MSG_FILE"
cat "$MSG_FILE.tmp" >> "$MSG_FILE"
rm "$MSG_FILE.tmp"
