#!/bin/sh

MSG_FILE=$1
COMMIT_SOURCE=$2
if [ "$COMMIT_SOURCE" = "merge" ] || [ "$COMMIT_SOURCE" = "commit" ]; then
  exit 0
fi

VERSION=$(cat version.txt)

sed -i.bak "1s/^^/[v$VERSION] /" "$MSG_FILE"
rm "$MSG_FILE.bak"
